import type { Machine, Task } from "./platform-types";

const safeKey = (value: string) => value.replace(/[^a-zA-Z0-9_-]/g, "-");
export const FILTER_TASK_NOTICE_DAYS = 14;

const localDateKey = (date: Date) =>
  `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;

const addLocalDays = (date: Date, days: number) => {
  const result = new Date(date.getFullYear(), date.getMonth(), date.getDate());
  result.setDate(result.getDate() + days);
  return localDateKey(result);
};

const sameTasks = (left: Task[], right: Task[]) =>
  left.length === right.length && left.every((task, index) => task === right[index]);

export function reconcileFilterReplacementTask(
  tasks: Task[],
  machine: Machine,
  assignedTo: string,
  now = new Date(),
) {
  const dueDate = machine.filterReplacementDue?.slice(0, 10) || "";
  const automationKey = dueDate ? `filter:${machine.id}:${dueDate}` : "";
  const isValidDate = /^\d{4}-\d{2}-\d{2}$/.test(dueDate);
  const isRelevant = isValidDate && dueDate <= addLocalDays(now, FILTER_TASK_NOTICE_DAYS);
  const withoutObsoletePending = tasks.filter(
    (task) =>
      task.machineId !== machine.id ||
      task.type !== "תחזוקת פילטר" ||
      !task.autoGenerated ||
      task.status === "בוצעה" ||
      (isRelevant && task.automationKey === automationKey),
  );

  if (!isRelevant || withoutObsoletePending.some((task) => task.automationKey === automationKey)) {
    return sameTasks(tasks, withoutObsoletePending) ? tasks : withoutObsoletePending;
  }

  const createdAt = now.toISOString();
  const customerLocation = [machine.site, machine.floor, machine.location]
    .filter(Boolean)
    .join(" · ");
  const task: Task = {
    id: `task-filter-${safeKey(machine.id)}-${dueDate}`,
    accountId: machine.accountId,
    machineId: machine.id,
    automationKey,
    autoGenerated: true,
    title: `החלפת פילטר · ${machine.model}${customerLocation ? ` · ${customerLocation}` : ""}`,
    type: "תחזוקת פילטר",
    dueDate,
    priority: "גבוהה",
    status: "פתוחה",
    assignedTo: assignedTo || "מנהל המערכת",
    createdAt,
    updatedAt: createdAt,
  };
  return [task, ...withoutObsoletePending];
}

export function updateTaskStatus(tasks: Task[], id: string, status: string, changedAt: string) {
  return tasks.map((task) => {
    if (task.id !== id || task.status === status) return task;
    return {
      ...task,
      status,
      updatedAt: changedAt,
      completedAt: status === "בוצעה" ? changedAt : undefined,
    };
  });
}
