import type { Machine, Task } from "./platform-types";

const safeKey = (value: string) => value.replace(/[^a-zA-Z0-9_-]/g, "-");

export function reconcileFilterReplacementTask(
  tasks: Task[],
  machine: Machine,
  assignedTo: string,
  now = new Date(),
) {
  const dueDate = machine.filterReplacementDue?.slice(0, 10) || "";
  const automationKey = dueDate ? `filter:${machine.id}:${dueDate}` : "";
  const withoutObsoletePending = tasks.filter(
    (task) =>
      task.machineId !== machine.id ||
      task.type !== "תחזוקת פילטר" ||
      task.status === "בוצעה" ||
      task.automationKey === automationKey,
  );

  if (!dueDate || withoutObsoletePending.some((task) => task.automationKey === automationKey)) {
    return withoutObsoletePending;
  }

  const createdAt = now.toISOString();
  const customerLocation = [machine.site, machine.floor, machine.location]
    .filter(Boolean)
    .join(" · ");
  const task: Task = {
    id: `task-filter-${safeKey(machine.id)}-${dueDate}`,
    accountId: machine.accountId,
    machineId: machine.id,
    automationKey,
    autoGenerated: true,
    title: `החלפת פילטר · ${machine.model}${customerLocation ? ` · ${customerLocation}` : ""}`,
    type: "תחזוקת פילטר",
    dueDate,
    priority: "גבוהה",
    status: "פתוחה",
    assignedTo: assignedTo || "מנהל המערכת",
    createdAt,
    updatedAt: createdAt,
  };
  return [task, ...withoutObsoletePending];
}

export function updateTaskStatus(tasks: Task[], id: string, status: string, changedAt: string) {
  return tasks.map((task) => {
    if (task.id !== id || task.status === status) return task;
    return {
      ...task,
      status,
      updatedAt: changedAt,
      completedAt: status === "בוצעה" ? changedAt : undefined,
    };
  });
}
